<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>ab67bc58-6cf2-4a3d-be56-2a4f22de521d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module']/div/div[2]/div[2]/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-hHTYSt.jWSUCo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>481b6fb6-5334-46c5-a671-4f00862e577b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hHTYSt jWSUCo</value>
      <webElementGuid>70b3f210-b04b-4b27-9a08-faeb64ffb003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>fdeafbde-7f49-4ed5-b481-405207868149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module&quot;)/div[@class=&quot;sc-iBYQkv iVbAYJ&quot;]/div[@class=&quot;sc-ftTHYK hMCeBf&quot;]/div[@class=&quot;sc-bqWxrE cqjFBF&quot;]/div[@class=&quot;sc-ksBlkl docfmj hidden&quot;]/div[3]/button[@class=&quot;sc-hHTYSt jWSUCo&quot;]</value>
      <webElementGuid>5135cb3d-a8b5-45f8-a989-6a2e6776a79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module']/div/div[2]/div[2]/div/div[3]/button</value>
      <webElementGuid>0d54eb08-d2df-42f7-ac96-1eab2d374764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember this browser for 30 days'])[1]/following::button[1]</value>
      <webElementGuid>33244570-dc98-4527-bcd7-f594f682307c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification code'])[1]/following::button[1]</value>
      <webElementGuid>8499ff9f-e692-4962-a558-a7407ce981b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help? Please contact support at (800) 970-5875 Ext 2'])[1]/preceding::button[1]</value>
      <webElementGuid>321ab7fb-d03d-442d-a85a-9f2ca313389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>de6ec0f4-330a-458c-923d-89e6be36ecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>68904f67-aa09-4d1e-8a53-ea36b6ea8e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>223a253f-29af-47c5-9cf3-97e534af9f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
