<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Doctors</name>
   <tag></tag>
   <elementGuidId>cdf1892d-a5bd-4f86-ba5b-04c97fdc1599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Doctors&quot;] > span.nav-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afaf1971-afad-4073-838e-6accc201a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-label</value>
      <webElementGuid>ea5ff5cb-5c97-4e71-95cf-028832b2597d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doctors</value>
      <webElementGuid>9ae89bae-57ee-45d6-abfb-b8f9683485a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[3]/a[1]/span[@class=&quot;nav-label&quot;]</value>
      <webElementGuid>b43323b5-be9c-4485-a068-b532b6eaef9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[3]/a/span</value>
      <webElementGuid>13fd8981-3747-4c1f-baa3-418bdc735ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[1]</value>
      <webElementGuid>1e5657d4-6432-4ae0-b348-0b3ebb2d0d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Raul L Garcia'])[1]/following::span[2]</value>
      <webElementGuid>fc2207cc-5f0f-42dc-87e6-bf66ab3cea89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specialties'])[1]/preceding::span[1]</value>
      <webElementGuid>da7e9d56-f424-4efb-8cff-19488f8e9751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CPT Questions'])[1]/preceding::span[2]</value>
      <webElementGuid>18a910ff-e4cf-43c3-8f3a-c81f3c4272b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doctors']/parent::*</value>
      <webElementGuid>03f3983b-3af4-4c8a-9b2a-e5f486daeb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>039d6efc-99ea-46be-a7a6-e321fcd4eacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Doctors' or . = 'Doctors')]</value>
      <webElementGuid>85f0c064-46ba-46d7-b07f-ac9fcdc9ae56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
