<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_Helen Automated Chufe De Paredes</name>
   <tag></tag>
   <elementGuidId>3d38a107-8a6e-43a1-83b5-6b88b447b8f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mrnName']/code</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mrnName > code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>29af7645-a32b-4af4-9aca-1eb0a7f8b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Helen Automated Chufe De Paredes</value>
      <webElementGuid>92672079-0765-4856-92fb-58cf9a4d5d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mrnName&quot;)/code[1]</value>
      <webElementGuid>44ccec88-fa95-49ae-8f70-3f99a153394b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mrnName']/code</value>
      <webElementGuid>1c31360c-b1c2-46b1-8015-5630d783c103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The MRN was not found. Please try again, enter a new office or search by insurance.'])[1]/following::code[1]</value>
      <webElementGuid>d4407f3d-bcd3-4d0f-9038-ee562ac3040a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Helen Automated Chufe De Paredes']/parent::*</value>
      <webElementGuid>9a6cf898-b15b-4d67-871b-4ce0a8f04fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/code</value>
      <webElementGuid>2b0abad9-a5a6-4b56-babf-d1dce7d5eacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//code[(text() = 'Helen Automated Chufe De Paredes' or . = 'Helen Automated Chufe De Paredes')]</value>
      <webElementGuid>70285e58-aa2e-4bdc-9458-03e5b05e0646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
