<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Confirmation of Appointment Request</name>
   <tag></tag>
   <elementGuidId>7043191e-4044-46b7-b529-cc659deba16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Confirmation of Appointment Request']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3fad288d-fe63-41e8-b5bf-c6b8c3aab48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmation of Appointment Request</value>
      <webElementGuid>29fdeb51-0c0b-45c4-8066-826e81f3aba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divToPrint&quot;)/div[1]/div[2]/h1[1]</value>
      <webElementGuid>73b0bffc-e6ed-4999-86c0-3f456deafd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/63.LoginUserProviderCreateReferralInPersonAppointmenSearchByInsuranceAddNote/Page_ReferWell/iframe_Return to Dashboard_get_confirmation_frame</value>
      <webElementGuid>aadee756-3ded-4106-904a-04400708c598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divToPrint']/div/div[2]/h1</value>
      <webElementGuid>ca583d35-7b51-443d-aec7-c2fcf44ccc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rebequita Reffering, DO'])[1]/preceding::h1[1]</value>
      <webElementGuid>950e9e1a-4ffe-4805-8134-340c9ec40b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardiology'])[1]/preceding::h1[1]</value>
      <webElementGuid>b798a908-97f1-4cb6-8081-008766275f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmation of Appointment Request']/parent::*</value>
      <webElementGuid>68892754-35bc-4fdb-a947-8d0ec5a13dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a4daa73b-eff8-45a1-b9a5-f00c6b6322e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Confirmation of Appointment Request' or . = 'Confirmation of Appointment Request')]</value>
      <webElementGuid>a2dc66cc-e8a7-4dfb-8b27-2693ca006c76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
