<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Return to Dashboard_get_confirmation_frame</name>
   <tag></tag>
   <elementGuidId>f7cd0f00-8a12-4a09-9010-d5e6a2bbbb03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='get_confirmation_frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#get_confirmation_frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b46a2f27-ab16-4264-948d-c3bbced72aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get_confirmation_frame</value>
      <webElementGuid>22b9e8da-7602-4ae5-9657-aacd090ed5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qa.referwell.com/home/get_confirmation/402930/81552419/1/0/1</value>
      <webElementGuid>bcd7b782-86c6-4e8f-b31d-774a62d887ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get_confirmation_frame&quot;)</value>
      <webElementGuid>1ea71870-f10c-4946-8ef2-931e63555302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='get_confirmation_frame']</value>
      <webElementGuid>c46e7133-dcab-4039-ada0-b1ff61f73212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>67cc8ca1-184e-4c47-a775-6976a503d445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'get_confirmation_frame' and @src = 'https://qa.referwell.com/home/get_confirmation/402930/81552419/1/0/1']</value>
      <webElementGuid>c5ab232e-4eed-4a5a-a47a-62e79c854451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
