<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cancel_submit</name>
   <tag></tag>
   <elementGuidId>c02ac3f3-98c8-44f2-9d6b-6ab429099157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitbutton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12fcf77a-ab2f-43d0-a7f2-fe6085b3f817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19dc3bca-9290-465c-90b4-3d89fd2f70af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>620bf97d-cf23-4fae-88d4-053f18924991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitbutton</value>
      <webElementGuid>92ed7914-e5ac-4b16-b280-06527b7a1f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary add-app-save-btn util-once-only submitbutton click-stopper</value>
      <webElementGuid>79860207-dd15-480b-aa93-0d5472799db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>E-sign and Send Appointment</value>
      <webElementGuid>e693df96-fdfe-4ae3-b1ff-e9e4e9188334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitbutton&quot;)</value>
      <webElementGuid>eafaa1d2-638f-4132-9929-518d5c633b2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitbutton']</value>
      <webElementGuid>781e41b9-6aeb-42a5-a727-a7ce5b348617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patient_form']/div[2]/div[2]/input[2]</value>
      <webElementGuid>e002ad60-5b6a-4362-9038-ae6534d790c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>f0bdad02-0bce-4854-8c71-112f31252830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit' and @id = 'submitbutton']</value>
      <webElementGuid>3eee88ee-c040-4454-94e7-a4d9e013a79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
