<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Patient MRN_select-mrn</name>
   <tag></tag>
   <elementGuidId>3825ad96-9c22-489b-8459-4a18794c74b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-mrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='select-mrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24b33d2a-0213-468d-b9fe-015532595578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00dc02a7-025e-446b-b00c-678d4c1a75d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb26ce05-6406-4958-937a-4672697feea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-mrn</value>
      <webElementGuid>395f70d3-2818-49d5-a1a8-5e71a5b66c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>select-mrn</value>
      <webElementGuid>8cb42074-dac2-434d-99dc-b80a8938e78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type MRN</value>
      <webElementGuid>24a2b71b-343c-42d6-b1e6-de857b32a6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-mrn&quot;)</value>
      <webElementGuid>e06ce86c-704b-44af-b95f-b4c30de2e0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='select-mrn']</value>
      <webElementGuid>ed97987d-29c5-4841-ab05-f277dcaf0f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mrnSearch']/div/div/div/div[2]/input</value>
      <webElementGuid>ebf17a16-d3dc-4c9c-a4a2-6e660b098cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>efd1a282-0e2b-41ee-8401-6149d469ba63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'select-mrn' and @name = 'select-mrn' and @placeholder = 'Type MRN']</value>
      <webElementGuid>c2096f57-f9ec-4c9a-8aa6-f17fa51ddc90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
