<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DOB_dob-input</name>
   <tag></tag>
   <elementGuidId>6e40187b-28a8-4769-b333-ac81b4c492c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dob-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dob-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>607debb5-d13b-4f6b-b81e-cbd811b4bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control us-date-mask</value>
      <webElementGuid>1f8774ae-1678-488f-912a-a5d18ec8bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dob-input</value>
      <webElementGuid>69cfbf87-332b-45ce-8fc7-0e6cab52e645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>a844f264-2dd3-4592-9e7a-1edeb520735d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dob-input&quot;)</value>
      <webElementGuid>35c3315c-4227-40cd-afac-c9bdbee5ffe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dob-input']</value>
      <webElementGuid>b7f40630-a71b-46de-8555-08063c7da501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patient-lookup']/div[3]/div/input</value>
      <webElementGuid>f624c33a-8cd9-4463-b2f2-b01b6cc74b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0f845537-cd0d-4733-a008-1c9b7111a92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dob-input' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>fbf1f605-b32c-46f3-a224-39739cc3b252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
