<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1mrn14022023</name>
   <tag></tag>
   <elementGuidId>4eb7299f-47f0-42d6-82cf-a5e7201cfdc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add_patient']/div/div[2]/div[4]/div/div[2]/table/tbody/tr[37]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0c2a5630-deee-46e8-8eec-a3cd47f2f53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            1mrn14022023
                        </value>
      <webElementGuid>28a5834a-fca6-45a7-807c-d5596dd5e7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_patient&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;add-patient-body&quot;]/div[@class=&quot;row patint-lookup-suggested-pts&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover patient-lookup-suggestions&quot;]/tbody[1]/tr[@class=&quot;clickrow&quot;]/td[2]</value>
      <webElementGuid>1100b413-b613-4e76-81e6-ce19a9291688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_patient']/div/div[2]/div[4]/div/div[2]/table/tbody/tr[37]/td[2]</value>
      <webElementGuid>62e76305-574c-4fcd-aa30-7ee399736d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1mrn14022023']/parent::*</value>
      <webElementGuid>2b61cdc0-dda5-4beb-977e-5acc658e313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[37]/td[2]</value>
      <webElementGuid>6ceb72f0-80e8-4706-a9ec-9c1c9847aa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                            1mrn14022023
                        ' or . = '
                            1mrn14022023
                        ')]</value>
      <webElementGuid>b6b8b2d8-8c61-40fc-8c93-9873e57d6471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
